filebeat.inputs:
- type: log
  enabled: true
  paths: ["/home/jakub/Documents/WUT/ADT/PacketMonitor/log/*.log"]
  json.message_key: interface_name
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true

setup.kibana:
  host: "localhost:5601"

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  template.name: filebeat
  template.path: filebeat.template.json

